### ISSUE TITLE
Problem with Node? Netlify? Remix?

### ISSUE THREAD

**Issue by pschaeffer** [netlify/remix-compute#275]
### Describe the bug

I am getting an error when I try to run my application. I am not sure if this is a node error or Netlify error or a Remix error. See below. I get the error shown below. What does node:internal mean? I have no idea.

Function remix-server has returned an error: Invalid module "...uildserverserver.js" is not a valid package name imported from C:\Users\Peter\Documents\Visual_Studio_Code\Projects\WebApplication5\WebApplication5\my-remix-udemy-section3-netlify2.netlify\functions-serve.unzipped\remix-server\remix-server.mjs
TypeError: Invalid module "...uildserverserver.js" is not a valid package name imported from C:\Users\Peter\Documents\Visual_Studio_Code\Projects\WebApplication5\WebApplication5\my-remix-udemy-section3-netlify2.netlify\functions-serve.unzipped\remix-server\remix-server.mjs
at new NodeError (node:internal/errors:406:5)
at parsePackageName (node:internal/modules/esm/resolve:718:11)
at packageResolve (node:internal/modules/esm/resolve:740:5)
at moduleResolve (node:internal/modules/esm/resolve:838:20)
at defaultResolve (node:internal/modules/esm/resolve:1043:11)
at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:383:12)
at ModuleLoader.resolve (node:internal/modules/esm/loader:352:25)
at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:228:38)
at ModuleWrap. (node:internal/modules/esm/module_job:85:39)
at link (node:internal/modules/esm/module_job:84:36)

Response with status 500 in 446 ms.

### Steps to reproduce

Execute 'netlify serve'. For some reason 'netlify dev' works.

### Configuration

[build]
command = "npx prisma generate && npm run build"
publish = "build/client"

[dev]
command = "npm run dev"
framework = "vite"

# Set immutable caching for static files, because they have fingerprinted filenames

[[headers]]
for = "/build/*"

[headers.values]

"Cache-Control" = "public, max-age=31560000, immutable"

### Environment

Quite standard. The code below is being stored in .netlify/functions-server/.unzipped/remix-server/remix-server.mjs

import {createRequire as ___nfyCreateRequire} from "module";
import {fileURLToPath as ___nfyFileURLToPath} from "url";
import {dirname as ___nfyPathDirname} from "path";
let __filename=___nfyFileURLToPath(import.meta.url);
let __dirname=___nfyPathDirname(___nfyFileURLToPath(import.meta.url));
let require=___nfyCreateRequire(import.meta.url);

// .netlify/functions-internal/remix-server.mjs
import { default as default2 } from "....\buildserverserver.js";
var config = {
  name: "Remix server handler",
  generator: "@netlify/remix-adapter@2.3.0",
  path: "/*",
  preferStatic: true
};
export {
  config,
  default2 as default
};

**Comment by mrstork** [comment]
This has been resolved in https://github.com/netlify/remix-compute/pull/281.

Please ensure you are using `@netlify/remix-adapter@2.3.1` which includes the fix. Running `npm install` in the project directory should automatically install the latest version for you.

**Comment by pschaeffer** [comment]
I think I am running the correct version of Remix. See the attached files.
<img width="776" alt="Captur
<img width="853" alt="Capture2" src="https://github.com/netlify/remix-compute/assets/3717450/0c98a9c8-65b9-474b-bf07-31667934800d">
e1" src="https://github.com/netlify/remix-compute/assets/3717450/3526f45e-23d3-4182-a6fd-df1b9aa93f78">

**Comment by pschaeffer** [comment]
Hi Mateusz Bocian,

 

I ran ‘npm install’ and I still get 2.3.0. What am I doing wrong.

 

Thank you

 

Peter Schaeffer

**Comment by mrstork** [comment]
You can specify `"@netlify/remix-adapter": "^2.3.1",` in your [`package.json`](https://github.com/pschaeffer/my-remix-udemy-section3-netlify3/blob/main/package.json#L15) and then try running `npm install` once again.

**Comment by pschaeffer** [comment]
Hi Mateusz Bocian,

 

I upgraded to 2.3.1 as you suggested and then verified (using npm list) that I had 2.3.1.

 

Netlify4 (actually all lowercase) seems to work correctly with ‘netlify serve’ and ‘netlify dev’ (no quotes of course).

 

By contrast, netlify3 still has some problems. ‘netlify dev’ (no quotes of course) gets some errors. See Capture1.PNG and Capture2.PNG.

 

‘netlify serve’ (no quotes of course) gets some errors. See Capture3.PNG and Capture4.PNG and Capture5.PNG

 

Thank you

 

Peter Schaeffer

**Comment by pschaeffer** [comment]
<img width="675" alt="Capture1" src="https://github.com/netlify/remix-compute/assets/3717450/a2616523-c05c-4779-aacc-bd2397d7a603">
<img width="813" alt="Capture2" src="https://github.com/netlify/remix-compute/assets/3717450/9fa7e4d2-d57e-4a0a-b02b-e27348d4e2
<img width="623" alt="Capture3" src="https://github.com/netlify/remix-compute/assets/3717450/e2f7359
<img width="869" alt="Capture4" src="https://github.com/netlify/remix-compute/assets/3717450/32b1d108-266f-4446-acaf-f6ebee89e7
<img width="886" alt="Capture5" src="https://github.com/netlify/remix-compute/assets/3717450/780fe242-b6c4-4c05-aa32-3307fa5aae6d">
0d">
0-5346-4cbc-93d5-676dbcf5a95f">
4b">

**Comment by pschaeffer** [comment]
You should have all the screenshots at this point. I updated [my-remix-udemy-section3-netlify3](https://github.com/pschaeffer/my-remix-udemy-section3-netlify3) with the newest code. Note that this repository does not include the node_folders folder. It was too large for git.

**Comment by mrstork** [comment]
The second screenshot doesn't look to have uploaded properly, however based on the first screenshot alone this doesn't look to be related to the original issue you posted about (i.e. `TypeError: Invalid module "...uildserverserver.js" is not a valid package name imported from ...`).

When I download your repository `my-remix-udemy-section3-netlify3` I get the error `TypeError: Cannot convert object to primitive value`. I get this error when I run `remix vite:dev` as well as when I run `netlify serve`, which indicates to me this in not an issue with the `remix-adapter` but rather an issue with how your project has been configured.

If you are certain your project is configured correctly and the issue is elsewhere, then we need your help! Please open up a new issue in the appropriate repository (e.g. remix, remix-adapter, netlify-cli, node), and please include a minimal reproducible example to help the community zero in on the root cause of the problem. Here is [a helpful resource describing how to create minimal reproducible examples ](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by pschaeffer** [comment]
I am not sure where the actual problem in netlify3 is. Some files are attached.
<img width="910" alt="Capture1" src="https://github.com/netlify/remix-compute/assets/3717450/f5ae456c-4378-4362-9444-387c63a3fae9">
<img width="678" alt="Capture2" src="https://github.com/netlify/remix-compute/assets/3717450/5f6ae20e-f6a6-4da3-bb11-40a082d6587f">
I got those images after I entered a 'netlify dev' (without the quotes) command
